name: Build & Release
on: [push]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - run: yarn install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
      - run: yarn build
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
          API_VERSION: ${{ env.GITHUB_SHA }}

      - uses: zuplo/deploy-zup-action@main
        with:
          project: zuplo-ecommerce-legacy
          account_id: 4f59a390b9f139a4a82b757edd3c71dd
          api_token: ${{ secrets.ZUPLO_CF_API_TOKEN }}
