name: Build & Release
on: [push]

jobs:
  build:
    name: Build & Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"

      - run: yarn install
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
      - run: yarn zuplo build
        env:
          GITHUB_NPM_TOKEN: ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
          GIT_SHA: ${{ github.sha }}
          API_VERSION: ${{ github.run_id }}
      - run: yarn lint

      - run: npm config set @zuplo:registry https://npm.pkg.github.com
      - run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GH_NPM_PACKAGE_READ_TOKEN }}
      - run: npm install @zuplo/orchestration -g

      - name: Deploy (Production)
        run: zops app:deploy . --name $ZUP_NAME
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          CF_ACCOUNT_ID: 4f59a390b9f139a4a82b757edd3c71dd
          CF_API_TOKEN: ${{ secrets.ZUPLO_CF_API_TOKEN }}
          ZUP_NAME: ecommerce-sample-api
